twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        jwt_token: '@App\Service\JwtToken'
        push_token: '@App\Service\PushToken'

when@test:
    twig:
        strict_variables: true
