version: '3.5'

services:
  mysql:
    build:
      context: ./docker/mysql
    restart: always
    volumes:
      - dbmysql:/var/lib/mysql
    ports:
      - "3307:3306"

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
    container_name: vote-php

  websocket:
    build:
      context: ./docker/websocket
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "6001:6001"

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/logs:/var/log

  redis:
    image: redis
    container_name: redis_redis

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':49150'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8080 http://localhost:8080
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

volumes:
  dbmysql:

###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
    driver: local

networks:
  default:
    name: vote-game