version: '3.5'

services:
  mysql:
    build:
      context: ./docker/mysql
    restart: always
    volumes:
      - dbmysql:/var/lib/mysql
    ports:
      - "3307:3306"

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
    container_name: vote-php

  websocket:
    build:
      context: ./docker/websocket
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "6001:6001"

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/logs:/var/log

  redis:
    image: redis
    container_name: redis_redis

volumes:
  dbmysql:
    driver: local

networks:
  default:
    name: vote-game